2024-06-18 14:21:44,344 INFO    StreamThr :57923 [internal.py:wandb_internal():85] W&B internal server running at pid: 57923, started at: 2024-06-18 14:21:44.343547
2024-06-18 14:21:44,345 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status
2024-06-18 14:21:44,347 INFO    WriterThread:57923 [datastore.py:open_for_write():87] open: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/run-tq7sn00n.wandb
2024-06-18 14:21:44,348 DEBUG   SenderThread:57923 [sender.py:send():379] send: header
2024-06-18 14:21:44,365 DEBUG   SenderThread:57923 [sender.py:send():379] send: run
2024-06-18 14:21:45,233 INFO    SenderThread:57923 [dir_watcher.py:__init__():211] watching files in: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files
2024-06-18 14:21:45,233 INFO    SenderThread:57923 [sender.py:_start_run_threads():1188] run started: tq7sn00n with start time 1718713304.344353
2024-06-18 14:21:45,248 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: check_version
2024-06-18 14:21:45,249 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: check_version
2024-06-18 14:21:45,373 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: run_start
2024-06-18 14:21:45,378 DEBUG   HandlerThread:57923 [system_info.py:__init__():26] System info init
2024-06-18 14:21:45,378 DEBUG   HandlerThread:57923 [system_info.py:__init__():41] System info init done
2024-06-18 14:21:45,378 INFO    HandlerThread:57923 [system_monitor.py:start():194] Starting system monitor
2024-06-18 14:21:45,378 INFO    SystemMonitor:57923 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-18 14:21:45,378 INFO    HandlerThread:57923 [system_monitor.py:probe():214] Collecting system info
2024-06-18 14:21:45,379 INFO    SystemMonitor:57923 [interfaces.py:start():188] Started cpu monitoring
2024-06-18 14:21:45,382 INFO    SystemMonitor:57923 [interfaces.py:start():188] Started disk monitoring
2024-06-18 14:21:45,384 INFO    SystemMonitor:57923 [interfaces.py:start():188] Started gpuapple monitoring
2024-06-18 14:21:45,385 INFO    SystemMonitor:57923 [interfaces.py:start():188] Started memory monitoring
2024-06-18 14:21:45,385 INFO    SystemMonitor:57923 [interfaces.py:start():188] Started network monitoring
2024-06-18 14:21:45,467 ERROR   HandlerThread:57923 [gpu_apple.py:probe():176] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:21:45,469 DEBUG   HandlerThread:57923 [system_info.py:probe():152] Probing system
2024-06-18 14:21:45,472 DEBUG   HandlerThread:57923 [system_info.py:_probe_git():137] Probing git
2024-06-18 14:21:45,485 DEBUG   HandlerThread:57923 [system_info.py:_probe_git():145] Probing git done
2024-06-18 14:21:45,485 DEBUG   HandlerThread:57923 [system_info.py:probe():200] Probing system done
2024-06-18 14:21:45,486 DEBUG   HandlerThread:57923 [system_monitor.py:probe():223] {'os': 'macOS-14.0-arm64-arm-64bit', 'python': '3.11.4', 'heartbeatAt': '2024-06-18T12:21:45.469714', 'startedAt': '2024-06-18T12:21:44.337684', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/philip/Desktop/Bachelor thesis project/transformer_train.py', 'codePathLocal': 'transformer_train.py', 'codePath': 'transformer_train.py', 'git': {'remote': 'https://github.com/Rockyph/Bachelor-thesis-project.git', 'commit': '88d29ba1325adde1e67752ecb38bc6337406ce9a'}, 'email': 'philipchristianrocki@gmail.com', 'root': '/Users/philip/Desktop/Bachelor thesis project', 'host': 'Philip.local', 'username': 'philip', 'executable': '/usr/local/bin/python3', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 460.4317207336426, 'used': 13.794960021972656}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-06-18 14:21:45,486 INFO    HandlerThread:57923 [system_monitor.py:probe():224] Finished collecting system info
2024-06-18 14:21:45,486 INFO    HandlerThread:57923 [system_monitor.py:probe():227] Publishing system info
2024-06-18 14:21:45,486 INFO    HandlerThread:57923 [system_monitor.py:probe():229] Finished publishing system info
2024-06-18 14:21:45,488 DEBUG   SenderThread:57923 [sender.py:send():379] send: files
2024-06-18 14:21:45,488 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-06-18 14:21:45,542 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:21:45,550 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: python_packages
2024-06-18 14:21:45,550 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: python_packages
2024-06-18 14:21:45,551 DEBUG   SenderThread:57923 [sender.py:send():379] send: telemetry
2024-06-18 14:21:45,551 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:45,551 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: stop_status
2024-06-18 14:21:45,551 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: stop_status
2024-06-18 14:21:46,078 INFO    wandb-upload_0:57923 [upload_job.py:push():130] Uploaded file /var/folders/fk/p554nvt53n7d415kgm1817100000gn/T/tmpi0m4j0miwandb/ioebl7ww-wandb-metadata.json
2024-06-18 14:21:46,237 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/requirements.txt
2024-06-18 14:21:46,237 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-metadata.json
2024-06-18 14:21:46,237 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:21:46,589 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:46,599 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:46,599 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:46,599 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:46,600 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:47,232 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:47,233 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:47,233 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:47,233 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:47,239 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:21:47,594 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:47,667 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:21:47,853 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:47,853 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:47,853 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:47,853 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:48,244 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:21:48,245 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:21:48,493 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:48,493 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:48,493 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:48,493 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:48,599 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:49,109 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:49,109 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:49,109 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:49,110 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:49,251 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:21:49,600 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:49,700 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:49,701 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:49,701 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:49,701 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:21:49,702 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:49,782 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:21:50,256 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:21:50,256 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:21:50,297 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:50,297 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:50,297 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:50,298 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:50,605 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:50,880 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:50,881 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:50,881 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:50,881 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:51,261 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:21:51,473 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:51,474 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:51,474 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:51,474 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:51,607 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:51,907 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:21:52,082 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:52,083 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:52,083 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:52,083 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:52,267 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:21:52,267 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:21:52,609 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:52,664 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:21:52,664 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:21:52,664 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:21:52,665 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:21:53,272 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:21:53,610 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:54,016 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:21:54,277 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:21:54,615 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:54,761 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:21:55,278 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:21:55,620 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:56,131 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:21:56,621 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:57,623 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:58,239 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:21:58,629 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:21:59,632 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:00,346 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:00,556 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: stop_status
2024-06-18 14:22:00,556 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: stop_status
2024-06-18 14:22:00,634 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:00,813 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:01,639 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:02,454 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:02,641 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:03,643 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:04,558 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:04,645 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:05,650 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:06,573 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:06,652 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:06,669 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:07,655 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:08,658 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:08,781 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:09,660 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:10,665 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:10,891 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:11,581 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:11,668 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:12,675 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:13,022 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:13,676 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:14,679 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:15,139 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:15,560 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: stop_status
2024-06-18 14:22:15,560 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: stop_status
2024-06-18 14:22:15,684 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:16,686 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:16,716 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:17,255 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:17,378 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/config.yaml
2024-06-18 14:22:17,688 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:18,690 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:19,373 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:19,691 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:20,697 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:21,483 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:21,697 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:22,594 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:22,699 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:23,592 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:23,703 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:24,707 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:25,712 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:25,751 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:26,717 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:27,598 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:27,722 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:27,878 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:28,723 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:29,725 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:29,997 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:30,562 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: stop_status
2024-06-18 14:22:30,563 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: stop_status
2024-06-18 14:22:30,730 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:31,733 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:32,116 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:32,733 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:32,735 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:33,735 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:34,235 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:34,737 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:35,740 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:36,348 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:36,741 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:37,744 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:38,164 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:38,165 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:38,165 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:38,165 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:38,166 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:38,481 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:22:38,545 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:38,748 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:38,910 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:38,910 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:38,911 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:38,911 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:39,486 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:22:39,486 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:22:39,521 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:39,522 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:39,522 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:39,522 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:39,753 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:40,134 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:40,135 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:40,135 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:40,135 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:40,491 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:22:40,491 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:22:40,670 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:40,741 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:40,742 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:40,742 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:40,743 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:40,754 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:41,338 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:41,338 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:41,338 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:41,339 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:41,496 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:22:41,756 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:41,948 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:41,948 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:41,948 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:41,949 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:42,502 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:22:42,506 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:22:42,583 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:42,583 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:42,583 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:42,583 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:42,758 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:42,838 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:43,250 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:43,251 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:43,251 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:43,252 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:43,252 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:43,504 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:22:43,763 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:43,864 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:43,864 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:43,864 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:43,864 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:44,510 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:22:44,510 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:22:44,519 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: partial_history
2024-06-18 14:22:44,520 DEBUG   SenderThread:57923 [sender.py:send():379] send: history
2024-06-18 14:22:44,520 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: summary_record
2024-06-18 14:22:44,520 INFO    SenderThread:57923 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-18 14:22:44,764 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:44,949 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:45,386 DEBUG   SystemMonitor:57923 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-18 14:22:45,387 DEBUG   SenderThread:57923 [sender.py:send():379] send: telemetry
2024-06-18 14:22:45,387 DEBUG   SenderThread:57923 [sender.py:send():379] send: stats
2024-06-18 14:22:45,514 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/wandb-summary.json
2024-06-18 14:22:45,515 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:22:45,567 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: stop_status
2024-06-18 14:22:45,568 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: stop_status
2024-06-18 14:22:45,769 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:46,520 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:22:46,771 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:47,074 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:47,524 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/output.log
2024-06-18 14:22:47,774 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:48,777 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:48,784 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:49,186 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:49,534 INFO    Thread-12 :57923 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/files/config.yaml
2024-06-18 14:22:49,777 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:50,782 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:51,287 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:51,787 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:52,788 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:53,396 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:53,789 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:54,626 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:54,791 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:55,507 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:55,797 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:56,801 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:57,734 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:22:57,803 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:58,808 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:59,636 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:22:59,810 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:22:59,844 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:23:00,573 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: stop_status
2024-06-18 14:23:00,573 DEBUG   SenderThread:57923 [sender.py:send_request():406] send_request: stop_status
2024-06-18 14:23:00,814 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:01,816 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:01,961 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:23:02,821 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:03,823 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:04,069 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:23:04,777 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:23:04,827 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:05,830 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:06,178 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:23:06,834 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:07,838 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:08,288 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:23:08,841 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:09,844 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:10,397 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:23:10,629 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: status_report
2024-06-18 14:23:10,849 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:11,852 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:12,508 ERROR   gpuapple  :57923 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-18 14:23:12,854 DEBUG   HandlerThread:57923 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-18 14:23:13,617 INFO    memory    :57923 [interfaces.py:monitor():138] Process proc.memory.rssMB has exited.
2024-06-18 14:23:13,618 INFO    cpu       :57923 [interfaces.py:monitor():138] Process cpu has exited.
2024-06-18 14:23:13,618 DEBUG   SystemMonitor:57923 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-06-18 14:23:13,619 DEBUG   SystemMonitor:57923 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-06-18 14:23:13,621 DEBUG   SenderThread:57923 [sender.py:send():379] send: stats
2024-06-18 14:23:13,792 WARNING StreamThr :57923 [internal.py:is_dead():413] Internal process exiting, parent pid 57913 disappeared
2024-06-18 14:23:13,793 ERROR   StreamThr :57923 [internal.py:wandb_internal():151] Internal process shutdown.
2024-06-18 14:23:14,623 INFO    WriterThread:57923 [datastore.py:close():296] close: /Users/philip/Desktop/Bachelor thesis project/wandb/run-20240618_142144-tq7sn00n/run-tq7sn00n.wandb
2024-06-18 14:23:14,626 INFO    HandlerThread:57923 [handler.py:finish():882] shutting down handler
2024-06-18 14:23:14,626 INFO    HandlerThread:57923 [system_monitor.py:finish():203] Stopping system monitor
2024-06-18 14:23:14,626 INFO    HandlerThread:57923 [interfaces.py:finish():200] Joined cpu monitor
2024-06-18 14:23:14,626 INFO    HandlerThread:57923 [interfaces.py:finish():200] Joined disk monitor
2024-06-18 14:23:14,626 INFO    HandlerThread:57923 [interfaces.py:finish():200] Joined gpuapple monitor
2024-06-18 14:23:14,626 INFO    HandlerThread:57923 [interfaces.py:finish():200] Joined memory monitor
2024-06-18 14:23:14,626 INFO    HandlerThread:57923 [interfaces.py:finish():200] Joined network monitor
2024-06-18 14:23:14,626 INFO    SenderThread:57923 [sender.py:finish():1608] shutting down sender
2024-06-18 14:23:15,803 INFO    MainThread:57923 [internal.py:handle_exit():75] Internal process exited
